Rubay.Web.App/Controllers/CartAccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rubay.Web.App.Areas.Identity.Data;
using Rubay.Web.App.Models;

namespace Rubay.Web.App.Controllers;

[Authorize]
public class CartAccountController : Controller
{
    private readonly UserManager<AccountUser> _userManager;
    private readonly IApiResponse _apiResponse;

    public CartAccountController(UserManager<AccountUser> userManager, IApiResponse apiResponse) => 
        (_userManager, _apiResponse) = (userManager, apiResponse);

    public async Task<IActionResult> Index()
    {
        var cartApiUrl = Environment.GetEnvironmentVariable("CartApiUrl");
        var user = await _userManager.GetUserAsync(User);
        var cart = await _apiResponse.GetFromJsonAsync<CartViewResult>($"{cartApiUrl}/api/cart/{user.Id}") ?? new CartViewResult(user.UserName,new List<ProductViewResult>());

        return View(cart);
    }

    public async Task<IActionResult> DeleteFromCart(ProductViewResult productViewResult)
    {
        var cartApiUrl = Environment.GetEnvironmentVariable("CartApiUrl");
        var itemApiUrl = Environment.GetEnvironmentVariable("ItemApiUrl");
        var user = await _userManager.GetUserAsync(User);

        await _apiResponse.GetResponseAsync($"{cartApiUrl}/api/cart/{user.Id}/delete/{productViewResult.ModelId}", HttpMethod.Delete);
        await _apiResponse.GetResponseAsync($"{itemApiUrl}/api/item/update/{productViewResult.ModelId}/{productViewResult.Quantity}", HttpMethod.Put);


        return RedirectToAction("Index");
    }
}

Rubay.Web.App/Controllers/CheckStatusController.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Rubay.Web.App.Models;

namespace Rubay.Web.App.Controllers;

public class CheckStatusController : Controller
{
    private readonly IApiResponse _apiResponse;

    public CheckStatusController(IApiResponse apiResponse) => _apiResponse = apiResponse;

    public async Task<IActionResult> Index()
    {
        var itemApiUrl = Environment.GetEnvironmentVariable("ItemApiUrl");
        var cartApiUrl = Environment.GetEnvironmentVariable("CartApiUrl");
        var responseItem = await _apiResponse.GetResponseAsync($"{itemApiUrl}/api/KeepAlive", HttpMethod.Get);
        var responseCart = await _apiResponse.GetResponseAsync($"{cartApiUrl}/api/KeepAlive", HttpMethod.Get);

        var result = new List<CheckStatusResult> {
            new CheckStatusResult("ItemApi",responseItem.RequestMessage.RequestUri.Host, responseItem.StatusCode == HttpStatusCode.OK),
            new CheckStatusResult("CartApiUrl",responseCart.RequestMessage.RequestUri.Host,responseCart.StatusCode == HttpStatusCode.OK),
        };

        return View(result);
    }
}

Rubay.Web.App/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rubay.Data.Common.GeneralExtensions;
using Rubay.Web.App.Areas.Identity.Data;
using Rubay.Web.App.Models;

namespace Rubay.Web.App.Controllers;

public class ProductController : Controller
{
    private readonly UserManager<AccountUser> _userManager;
    private readonly IApiResponse _apiResponse;

    public ProductController(UserManager<AccountUser> userManager, IApiResponse apiResponse) => 
        (_userManager, _apiResponse) = (userManager, apiResponse);

    public async Task<IActionResult> Index()
    {
        var itemApiUrl = Environment.GetEnvironmentVariable("ItemApiUrl");
        var products = await _apiResponse.GetFromJsonAsync<IEnumerable<ProductViewResult>>($"{itemApiUrl}/api/item");

        return View(products);
    }

    [Authorize]
    public async Task<IActionResult> InsertToCart(ProductViewResult productViewResult)
    {
        var cartApiUrl = Environment.GetEnvironmentVariable("CartApiUrl");
        var itemApiUrl = Environment.GetEnvironmentVariable("ItemApiUrl");

        var user = await _userManager.GetUserAsync(User);

        var newProduct = productViewResult with { Quantity = 1};

        await _apiResponse.GetResponseAsync($"{cartApiUrl}/api/cart/{user.Id}/insert/{newProduct.ToJson()}", HttpMethod.Post);
        await _apiResponse.GetResponseAsync($"{itemApiUrl}/api/item/update/{newProduct.ModelId}/{-newProduct.Quantity}", HttpMethod.Put);

        return RedirectToAction("Index");
    }
}

Rubay.Web.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rubay.Web.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rubay Web App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CheckStatus" asp-action="Index">Status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CartAccount" asp-action="Index">Cart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Market Products</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>